name: Build APK

on:
 push: 
   branches: [ main ]
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 下载代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 设置 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Fix gradlew line endings
        run: sed -i 's/\r$//' gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      # --- 新增签名步骤 ---
      
      - name: 生成临时签名密钥
        run: |
           keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias myalias -storepass password789 -keypass password789 -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, S=Unknown, C=Unknown"
      - name: 用 jarsigner 签名 APK
        run: |
           jarsigner -verbose -keystore temp-key.jks -storepass temp123 -keypass temp123 -signedjar app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/app-release.apk tempalias

      # 动态改名
      - name: Rename APK
        run: |
           VERSION=$(grep versionName app/build.gradle | awk '{print $2}' | tr -d '"')
           DATE=$(date +%Y%m%d)
           NEW_NAME="X-screenv${VERSION}_${DATE}.apk"
           mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/$NEW_NAME
           echo "APK_FILE=app/build/outputs/apk/release/$NEW_NAME" >> $GITHUB_ENV
      
      - name: Upload Release APK
        uses: softprops/action-gh-release@v2
        with:
          name: X-screen-v${{ github.run_number }}  # 用构建号作为版本标签，每次构建都会自动生成新标签
          files: ${{ env.APK_FILE }}
          tag_name: latest
          overwrite_files: true
